---
name: Christian H.
surname: Holland
position: "PhD student"
address: "BioQuant, Heidelberg University"
phone: +49 (0) 176 4344 9810
# www: "https://christianholland.herokuapp.com"
email: "cholland2408@gmail.com"
twitter: mr_netherlands
github: christianholland
aboutme: "Data scientist tackling biomedical challenges"
date: "`r format(Sys.time(), '%B %Y')`"
# headXcolor: "000000"
orcid: 0000-0002-3060-5786
# profilepic: "./img/profile.jpeg"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = F)
library(vitae)
```

# Education
```{r education}
readr::read_csv2("entries/education.csv") %>%
  detailed_entries(degree, year, institution, where, description)
```

# Working Experience
```{r working}
readr::read_csv2("entries/experience.csv") %>%
  detailed_entries(degree, year, institution, where, description)
```

# Teaching Experience
```{r teaching}
readr::read_csv2("entries/teaching.csv") %>%
  detailed_entries(degree, year, institution, where)
```

# Skills
```{r skills}
readr::read_csv2("entries/skills.csv") %>%
  group_by(category) %>%
  summarise(skill = stringr::str_c(skill, collapse = ", ")) %>%
  mutate(category = factor(category, levels = c(
    "Programming", "Packages",
    "Tools"
  ))) %>%
  arrange(category) %>%
  detailed_entries(what = skill, with = category)
```

# Software development
```{r software}
sofware <- tibble::tribble(
  ~package, ~language, ~timezone, ~details,
  "Bioconductor package", "dorothea", "Available since Bioc 3.11", c("Tool to infer transcripion factor activities from gene expression data (Lead developer)"),
  "Bioconductor package", "progeny", "Available since Bioc 3.6", "Tool to infer pathway activities from gene expression data (Contributor)"
)
sofware %>%
  detailed_entries(what = package, with = language, where = timezone, 
                   why = details)
```


# Conferences Attended
```{r conferences}
readr::read_csv2("entries/conferences.csv") %>%
  detailed_entries(description, year, which, where)
```

# Selected Publications
```{r publications}
# library(dplyr)
# library(scholar)
# id = "h_y2uTwAAAAJ"
# l = scholar::get_publications(id) %>%
#   as_tibble() %>%
#   mutate(id = id) %>%
#   slice(1) %>%
#   mutate(author = purrr::map2(id, pubid, get_complete_authors)) %>%
#   # mutate(author = purrr::map2(id, pubid, function(x,y) {
#   #   res = get_complete_authors(x,y) %>%
#   #     str_replace("Christian H Holland", "\textbf{Christian H Holland}")
#   #   print(res)
#   #   return(res)
#   # })) %>%
#   unnest(author) %>%
#   transmute(bibtype = "Article", author = as.character(author),
#             title = as.character(title),
#             journaltitle = as.character(journal), year, key = row_number()) #%>%
#
# l %>%
#   RefManageR::as.BibEntry() %>%
#   RefManageR::WriteBib("references2.bib")

#
# x = scholar::get_complete_authors(key, "UeHWp8X0CEIC")
# x = scholar::get_publications("h_y2uTwAAAAJ") %>%
#   filter(cites > 1) %>%
#   filter(!stringr::str_detect(author, "Tajti")) %>%
#   distinct(title, .keep_all = TRUE) %>%
#   arrange(-year) %>%
#   slice(1) %>%
#   transmute(bibtype = "Article", author = as.character(author),
#             title = as.character(title),
#             journaltitle = as.character(journal), year, key = row_number()) %>%
#   RefManageR::as.BibEntry() %>%
#   RefManageR::WriteBib("references2.bib")

bibliography_entries("references.bib") %>%
  arrange()
```

```{r map, eval=FALSE, include=FALSE}
load.fontawesome()
uni <- fontawesome("fa-university")
work <- fontawesome("fa-briefcase")

world <- getMap(resolution = "high")
world <- world %>% st_as_sf()
cities <- st_sfc(
  st_point(c(-79.00453, -2.90055)),
  st_point(c(-9.13333, 38.71667)),
  st_point(c(7.6261, 51.9607)),
  st_point(c(12.9864, 47.8029))
) %>%
  st_sf(name = c("Cuenca, EC", "Lisbon, PT", "Münster, DE", "Salzburg, AT")) %>%
  st_set_crs(4326) %>%
  mutate(label = c(paste(work, uni, sep = " "), rep(uni, 2), work))
routes <- cities %>%
  points2line() %>%
  slice(c(2, 7, 12)) %>%
  st_segmentize(units::set_units(100, m))
ggplot(data = world) +
  geom_sf(color = "white", lwd = 0.1) +
  xlab("") +
  ylab("") +
  geom_sf_text(
    data = cities,
    aes(label = label),
    size = 3,
    color = "#009ACD",
    family = "fontawesome-webfont"
  ) +
  geom_sf(
    data = routes, color = "#009ACD", size = 0.5, alpha = 0.5, linetype = "dotted"
  ) +
  coord_sf(crs = "+proj=robin", xlim = c(-10000000, 4500000), ylim = c(-390000, 6100000)) +
  theme_minimal() +
  theme(
    panel.grid = element_line(color = "transparent"),
    plot.margin = margin(-1, 0, -1, 0, "cm"),
    axis.text = element_blank(),
    axis.title = element_blank()
  )
```
